// Dash Adventures: original picture books starring the family.
//
// {hero} and {sister} are filled in from books/private/cast.json when the
// books are generated. Dad, Mum and Dash are written as they are.
//
// Levels follow the ELS order Logan is taught. Level 1 matches his current
// school book (Tiger's Fish: Phase 3, one or two short sentences a page) and
// each level adds the next set of sounds. `challenge` lists the words a grown-up
// may need to help with, like the inside cover of his school books.
// `words` are the only words drawn inside a picture (labels, signs, sound effects).

const page = (text, scene, { cast = [], words = [], bubble = null, calm = null } = {}) => ({
  text, scene, cast, words, bubble, calm: calm || (bubble ? 'top-left' : null),
});
const say = (who, text) => ({ who, text });

const HOME = 'a cosy British terraced house with a small back garden, a lawn and a wooden shed';

export const BOOKS = [
  {
    id: 'big-green-egg',
    blurb: '{hero} and {sister} find a big green egg in Dad\'s shed. Crack! Out pops Dash, a tiny dinosaur with a taste for socks and hats. Can they hide him from Dad?',
    level: 1,
    title: 'The Big Green Egg',
    cast: ['hero', 'sister', 'dad', 'mum'],
    mystery: 'A big green egg... what is inside?',
    cover: {
      scene: `The doorway of a sunny wooden garden shed (${HOME}). {hero} and {sister} peer round the door at a huge glowing green egg with darker green spots, sitting in a flower pot full of straw. A tiny crack in the egg shows one friendly, round cartoon eye peeping out.`,
      cast: ['hero', 'sister'],
    },
    practise: ['egg', 'shed', 'crack', 'chomp', 'quick', 'tail'],
    common: ['the', 'he', 'her', 'little', 'out', 'we'],
    challenge: ['dinosaur', 'coming'],
    before: 'Look at the cover. What do you think is inside the big green egg?',
    after: [
      'What did Dash chomp?',
      'Why did {hero} and {sister} put Dash in the box?',
      'How did Dad find out about Dash?',
      'What would you do if you found a big egg?',
    ],
    pages: [
      page('{hero} and {sister} are in Dad\'s shed.',
        'Inside a cosy, slightly messy wooden garden shed on a sunny morning: tools on hooks, plant pots, a wheelbarrow, sunbeams through a dusty window. {hero} and {sister} tiptoe in, curious. Behind a stack of flower pots something big and green is half hidden. A small hand-painted wooden sign hangs on the wall.',
        { cast: ['hero', 'sister'], words: ['Dad\'s shed'] }),
      page('{hero} spots a big green egg.',
        'Close-up: {hero} lifts a flower pot to reveal a huge egg, as big as a football, bright green with darker green spots, nestled in straw. {sister} peeks over his shoulder with wide eyes.',
        { cast: ['hero', 'sister'], words: ['egg'] }),
      page('{sister} taps it. Tap, tap, tap!',
        '{sister} gently taps the big green egg with one finger, little motion lines around her finger. {hero} holds his breath, hands on his cheeks.',
        { cast: ['hero', 'sister'] }),
      page('Crack! The egg splits.',
        'A zig-zag crack shoots across the big green egg, a chip of shell pops off and a soft golden glow leaks out. {hero} and {sister} jump back in surprise, hands up.',
        { cast: ['hero', 'sister'], words: ['CRACK!'] }),
      page('Out pops a little dinosaur!',
        'Dash bursts out of the top of the egg with a piece of shell on his head like a hat, arms wide and a huge happy grin. {hero} and {sister} stare, delighted.',
        { cast: ['hero', 'sister', 'dash'], bubble: say('dash', 'I am Dash!') }),
      page('Dash gets Dad\'s sock. Chomp, chomp!',
        'Dash has pulled a long stripy sock out of a laundry basket in the shed and is chomping the toe end, tugging it like a puppy. {sister} giggles; {hero} reaches for the sock.',
        { cast: ['hero', 'sister', 'dash'], words: ['CHOMP!'] }),
      page('Then he chomps Dad\'s hat!',
        'Dash is now inside Dad\'s floppy sun hat, which is far too big for him, nibbling the brim. Only his tail and feet poke out. {hero} and {sister} laugh.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('Dad is coming!',
        'Through the shed window we see Dad walking up the garden path holding a mug of tea. Inside the shed, {hero} and {sister} hurry Dash into a cardboard box.',
        { cast: ['hero', 'sister', 'dash', 'dad'], bubble: say('hero', 'Quick, Dash! Get in the box!'), words: ['box'] }),
      page('Dad looks in. He sees {hero} and {sister}.',
        'Dad stands in the shed doorway with his mug, eyebrows raised. {hero} and {sister} stand in front of the cardboard box with innocent, much-too-big smiles. The box flaps are shut and Dash is completely hidden inside: he cannot be seen anywhere in the picture.',
        { cast: ['hero', 'sister', 'dad'] }),
      page('But the box has a tail!',
        'Visual joke: behind the children, a little turquoise-green tail pokes out of the cardboard box and wags. Dad is looking at the children, not at the box.',
        { cast: ['hero', 'sister', 'dad'] }),
      page('Dad sits on the box.',
        'Dad is just sitting down on the cardboard box to drink his tea. The lid bulges up under him and his tea sloshes in surprise.',
        { cast: ['hero', 'sister', 'dad'], bubble: say('dash', 'Help!'), calm: 'top-right' }),
      page('Dad jumps up and lifts the lid.',
        'Dad holds the box lid, mouth wide open in amazement. Dash pops up wearing the stripy sock like a scarf, grinning and waving.',
        { cast: ['dad', 'dash', 'hero', 'sister'], bubble: say('dad', 'A dinosaur!') }),
      page('Mum runs in. Dash licks her chin.',
        'Mum arrives at the shed door. Dash has leapt into her arms and is licking her chin; she is laughing. {sister} clasps her hands hopefully.',
        { cast: ['mum', 'dash', 'sister', 'hero', 'dad'], bubble: say('sister', 'Can we keep him?') }),
      page('Mum and Dad nod. Yes!',
        'Mum and Dad look at each other and nod with big smiles. {hero} and {sister} cheer with arms in the air; Dash does a happy wiggle.',
        { cast: ['mum', 'dad', 'hero', 'sister', 'dash'] }),
      page('Now Dash naps in Dad\'s hat.',
        'Cosy evening bedroom with a night light: Dash curled up asleep inside Dad\'s floppy sun hat at the end of {hero}\'s bed, the stripy sock as his blanket. {hero} smiles from his pillow. The two halves of the green egg shell sit on the shelf.',
        { cast: ['hero', 'dash'] }),
    ],
    retell: [2, 4, 5, 8, 12, 15],
  },

  {
    id: 'dash-in-the-bath',
    blurb: 'It is bath night for Dash, but {sister} adds a bit too much soap. The foam fills the room, Dash goes missing, and Dad gets a very soapy surprise.',
    level: 1,
    title: 'Dash in the Bath',
    cast: ['hero', 'sister', 'dad', 'mum', 'dash'],
    cover: {
      scene: 'A family bathroom full of fluffy white foam. Dash sits in the bath wearing a tall foam hat and a foam beard. {hero} and {sister}, in pyjamas, kneel beside the tub laughing.',
      cast: ['hero', 'sister', 'dash'],
    },
    practise: ['bath', 'soap', 'foam', 'duck', 'splash', 'shock'],
    common: ['the', 'he', 'of', 'no', 'puts', 'me'],
    challenge: ['rubber', 'bigger'],
    before: 'Have you ever had too many bubbles in the bath? What do you think will happen?',
    after: [
      'What made the foam get so big?',
      'How did they find Dash?',
      'Why did Dad slip?',
      'What was the funniest part?',
    ],
    pages: [
      page('It is bath night for Dash.',
        'A warm family bathroom in the evening: a white bath filling from the tap, a yellow rubber duck, toothbrushes in a cup, fluffy towels. {hero} and {sister} in pyjamas kneel beside the bath. Dash stands on the edge, testing the water with one toe.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('Dash hops in. Splash!',
        'Dash cannonballs into the bath and a big splash of water flies up. {hero} and {sister} shield their faces, laughing.',
        { cast: ['hero', 'sister', 'dash'], words: ['SPLASH!'] }),
      page('He sits on a rubber duck.',
        'Dash floats proudly on top of a big yellow rubber duck like a ship\'s captain, one arm raised. {hero} and {sister} kneel by the bath with their sleeves rolled up.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('{sister} puts in lots of soap.',
        '{sister} squeezes a big bottle of bubble bath into the water and the first foam starts to rise. {hero} watches, eyes wide.',
        { cast: ['hero', 'sister', 'dash'], words: ['soap'] }),
      page('Foam! Foam! The foam gets big.',
        'A mountain of fluffy white foam rises above the bath. Dash peeks out of the top of it.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('It gets bigger and bigger!',
        'The foam spills over the sides of the bath onto the floor and keeps growing like a cloud. {hero} and {sister} lean back in surprise.',
        { cast: ['hero', 'sister'] }),
      page('The foam fills the room!',
        'The whole bathroom is filled with foam up to the children\'s chins; only their heads stick out. The mirror is half covered and the rubber duck floats on top.',
        { cast: ['hero', 'sister'] }),
      page('But Dash is lost in the foam!',
        '{hero} and {sister} look around in the sea of foam, worried. There is no sign of Dash, just the rubber duck bobbing on top.',
        { cast: ['hero', 'sister'] }),
      page('{hero} digs in the foam. No Dash.',
        '{hero} scoops big armfuls of foam, searching, foam on his nose.',
        { cast: ['hero'] }),
      page('{sister} digs in the foam. No Dash.',
        '{sister} searches the foam with both hands, a little foam beard on her chin.',
        { cast: ['sister'] }),
      page('Then a tail pops up. Then a big grin!',
        'Out of the foam pops a little turquoise-green tail, and next to it Dash\'s big grinning face appears. {hero} and {sister} point and cheer.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('Dash has a foam hat and a foam beard!',
        'Close-up of Dash proudly wearing a tall white foam top hat and a long white foam beard, like a tiny wizard. {hero} and {sister} laugh in the background.',
        { cast: ['dash', 'hero', 'sister'] }),
      page('Then Dad looks in. He gets a shock!',
        'Dad opens the bathroom door and a wave of foam pours out around his legs. His jaw drops.',
        { cast: ['dad'] }),
      page('Dad slips on the foam...',
        'Dad slips on the foam, legs in the air and arms flailing, in a funny cartoon pose. {hero}, {sister} and Dash gasp.',
        { cast: ['dad', 'hero', 'sister', 'dash'] }),
      page('SPLASH! Now Dad is in the bath!',
        'Dad sits in the bath fully dressed in his clothes, covered in foam, with a foam hat and foam beard just like Dash. Dash sits on Dad\'s head. {hero} and {sister} laugh; Mum is in the doorway holding a towel, laughing too.',
        { cast: ['dad', 'dash', 'hero', 'sister', 'mum'], words: ['SPLASH!'], bubble: say('dad', 'Is it bath night for me too?'), calm: 'top-right' }),
    ],
    retell: [2, 4, 7, 11, 14, 15],
  },

  {
    id: 'crab-grab',
    blurb: 'A cheeky gull grabs Dad\'s chips and Dash gives chase, straight into a rock pool where a crab grabs his tail. {hero} needs a clever plan.',
    level: 2,
    title: 'Crab Grab!',
    cast: ['hero', 'sister', 'dad', 'mum', 'dash'],
    cover: {
      scene: 'A sunny British beach with a pier and colourful beach huts. Dash stands in a rock pool with a red crab hanging on to his tail. A cheeky seagull flies overhead with a chip in its beak. {hero} and {sister} run towards him with a fishing net and a bucket.',
      cast: ['hero', 'sister', 'dash'],
    },
    practise: ['crab', 'grab', 'chips', 'gull', 'splash', 'stuck', 'fresh'],
    common: ['the', 'of', 'go', 'my', 'no', 'he'],
    challenge: ['after'],
    before: 'What do you think a crab might grab?',
    after: [
      'What did the gull take?',
      'Why did Dash jump into the rock pool?',
      'How did {hero} get the crab to let go?',
      'How do you think the gull felt at the end?',
    ],
    pages: [
      page('{hero}, {sister} and Dash dig in the sand.',
        'A sunny British beach with a pier and colourful beach huts in the distance. {hero} and {sister} dig a moat around a sandcastle with spades; Dash digs furiously with his little claws, sand flying.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('Dad has a bag of chips. Yum!',
        'Dad relaxes in a striped deckchair with an open paper bag of hot chips, eyes closed and smiling. Mum reads a book beside him. A seagull on a post eyes the chips.',
        { cast: ['dad', 'mum'], words: ['chips'] }),
      page('A big gull swoops down. Grab!',
        'A cheeky seagull swoops down, wings spread, and snatches a chip from the bag. Dad\'s eyes pop open.',
        { cast: ['dad'], words: ['GRAB!'], bubble: say('dad', 'Stop! My chips!'), calm: 'top-right' }),
      page('Dash runs after the gull.',
        'Dash sprints across the sand after the low-flying seagull, his little legs a blur, a determined look on his face. The gull has a chip in its beak.',
        { cast: ['dash'] }),
      page('The gull drops the chip. Plop! It lands in a rock pool.',
        'The chip falls from the gull\'s beak into a clear rock pool among seaweed-covered rocks. Little ripples spread out.',
        { words: ['PLOP!'] }),
      page('Dash jumps in to get it. Splash!',
        'Dash dives head first into the rock pool after the chip, water splashing up.',
        { cast: ['dash'], words: ['SPLASH!'] }),
      page('Snap! A crab grabs Dash\'s tail.',
        'A red crab clamps its claw on Dash\'s tail. Dash\'s eyes go huge. Tiny fish watch from the seaweed.',
        { cast: ['dash'], words: ['SNAP!'] }),
      page('Dash is stuck!',
        'Dash wriggles in the rock pool, waving his arms, while the crab holds on tight to his tail.',
        { cast: ['dash'], bubble: say('dash', 'Help! Help!') }),
      page('{hero} and {sister} run to the rock pool.',
        '{hero} and {sister} race across the sand towards the rocks, {sister} holding a fishing net and {hero} holding a bucket.',
        { cast: ['hero', 'sister'], words: ['net', 'bucket'] }),
      page('{hero} has a plan. He grabs the chip.',
        '{hero} crouches at the rock pool, reaching in to pick up the floating chip with a clever smile. {sister} holds the net ready.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('The crab lets go of Dash. It grabs the chip!',
        '{hero} dangles the chip over the water. The crab lets go of Dash\'s tail and snatches the chip with both claws, very pleased. Dash scrambles free into {sister}\'s net.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('Dash is free! {sister} hugs him.',
        '{sister} hugs a soggy, happy Dash wrapped in a beach towel. {hero} grins beside them.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('Dad gets a fresh bag of chips.',
        'Back at the deckchairs, Dad holds a new paper bag of chips and the whole family sits together in the sunshine.',
        { cast: ['dad', 'mum', 'hero', 'sister', 'dash'] }),
      page('Dash sits on top of the bag. No gull will get them now!',
        'Dash stands guard on top of the chip bag with folded arms, wearing tiny sunglasses and a stern face. The seagull sulks on a post. In the distance the crab happily munches its chip.',
        { cast: ['dash', 'dad', 'hero', 'sister'] }),
    ],
    retell: [3, 5, 7, 10, 11, 14],
  },

  {
    id: 'monster-in-the-garden',
    blurb: '{hero}, {sister} and Dash camp in the garden. Then... crunch, crunch, crunch! What is the big dark lump outside the tent?',
    level: 2,
    title: 'The Monster in the Garden',
    cast: ['hero', 'sister', 'dad', 'mum', 'dash'],
    cover: {
      scene: `Night in the back garden (${HOME}). A small green tent glows from the inside. On the tent wall is a huge funny lumpy shadow with long arms. An owl sits on the shed roof under the stars. Dash peeks out of the tent door.`,
      cast: ['dash'],
    },
    practise: ['camp', 'tent', 'torch', 'crunch', 'lump', 'hump', 'glint', 'munch'],
    common: ['they', 'the', 'all', 'little', 'again', 'he'],
    challenge: ['garden', 'monster', 'sleeping'],
    before: 'Have you ever slept in a tent? What might you hear at night?',
    after: [
      'What did {sister} think the lump was?',
      'What was it really?',
      'How did {hero} find out?',
      'Would you like to camp in the garden? Why?',
    ],
    pages: [
      page('{hero}, {sister} and Dash camp in the garden.',
        `Evening in the back garden (${HOME}): a small green tent on the lawn, fairy lights on the fence, the sky turning orange and purple. {hero} and {sister} carry sleeping bags and a torch; Dash carries a pillow bigger than he is.`,
        { cast: ['hero', 'sister', 'dash'] }),
      page('They get into the tent. It is dark.',
        'Inside the tent by torchlight: {hero} and {sister} snuggled in sleeping bags, Dash in a tiny sleeping bag between them, the torch beam on the tent roof.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('Hoot! An owl sits on the shed.',
        'The night garden from outside: moonlight, stars, an owl with big round eyes on the shed roof, and the tent glowing softly on the lawn.',
        { words: ['HOOT!'] }),
      page('The stars glint. They all nod off.',
        'Inside the tent: {hero}, {sister} and Dash are drowsy, eyes closing. Through the tent\'s mesh window the stars twinkle.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('Then... crunch, crunch, crunch!',
        'Outside on the gravel path, something is coming closer: we only see the gravel and a long moonlit shadow. Inside the tent, eyes snap open.',
        { cast: ['hero', 'sister', 'dash'], words: ['CRUNCH!'] }),
      page('A big dark lump is next to the tent!',
        'From inside the tent: a huge strange silhouette on the tent wall, lumpy, with two tufts on top like horns. {hero} and {sister} clutch each other; Dash\'s back plates stand on end. Funny, not scary.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('It has long arms and a big hump!',
        'The silhouette on the tent wall stretches out long arms and has a big hump on its back. The children\'s eyes are as round as saucers, in a cartoonish way.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('{sister} yells. Dash jumps into a sleeping bag.',
        '{sister} yells with her hands up while Dash dives head first into {hero}\'s sleeping bag, only his tail sticking out.',
        { cast: ['hero', 'sister', 'dash'], bubble: say('sister', 'A monster!') }),
      page('{hero} grabs the torch. He points it at the lump.',
        '{hero}, brave, kneels at the tent door and shines the torch out through the open flap.',
        { cast: ['hero', 'sister'] }),
      page('It is not a monster. It is Dad!',
        'The torch beam shows Dad in a dressing gown and slippers, hair sticking up in two tufts, a rolled-up blanket on his back, carrying a tray with mugs of hot chocolate and buns. He squints into the light, grinning.',
        { cast: ['dad'], bubble: say('dad', 'Hot drinks and buns!'), calm: 'top-right' }),
      page('Dad gets in the tent too. It is a tight fit!',
        'Dad is squeezed into the small tent with {hero}, {sister} and Dash, his knees up by his ears, the tent bulging. Everyone laughs, holding mugs.',
        { cast: ['dad', 'hero', 'sister', 'dash'] }),
      page('They munch buns and look at the stars.',
        'The tent flap is open and everyone looks up at a sky full of stars. The owl watches from the shed. Dash holds a bun bigger than his head.',
        { cast: ['dad', 'hero', 'sister', 'dash'] }),
      page('Then... crunch, crunch! Not again!',
        'Everyone freezes mid-munch, eyes sliding sideways towards the dark garden.',
        { cast: ['dad', 'hero', 'sister', 'dash'], words: ['CRUNCH!'] }),
      page('A little fox sniffs at the tent. It gets a bun too!',
        'A cute fox cub pokes its nose through the tent flap. Dash kindly holds out a bun. Dad, {hero} and {sister} smile.',
        { cast: ['dad', 'hero', 'sister', 'dash'] }),
    ],
    retell: [1, 5, 6, 9, 10, 14],
  },

  {
    id: 'dads-big-snore',
    blurb: 'Dad\'s snore is so loud that books and socks fly round the house and Dash shoots into the air. {hero}\'s sock plan fails. Can Mum save the night?',
    level: 3,
    title: 'Dad\'s Big Snore',
    cast: ['hero', 'sister', 'dad', 'mum', 'dash'],
    cover: {
      scene: 'Night-time bedroom. Dad is fast asleep in bed and a giant swirly snore is blowing teddy bears, socks and books round the room. {hero} and {sister} hang on to the bedpost in their pyjamas. Dash flies past holding his blanket.',
      cast: ['dad', 'hero', 'sister', 'dash'],
    },
    practise: ['loud', 'round', 'mouth', 'away', 'dream', 'cries'],
    common: ['so', 'like', 'she', 'all', 'they', 'puts'],
    challenge: ['snore', 'snores', 'snoring', 'asleep', 'curtains'],
    before: 'Does anyone in your house snore? What does it sound like?',
    after: [
      'Why did the toys float round the room?',
      'What did {hero} try first? Did it work?',
      'How did Mum stop the snoring?',
      'Who was snoring at the end?',
    ],
    pages: [
      page('It is night. Dad is fast asleep.',
        'A cosy bedroom at night with moonlight through the curtains. Dad is asleep on his back with his mouth a little open; Mum is asleep beside him wearing an eye mask. Dash sleeps in a tiny basket on the windowsill.',
        { cast: ['dad', 'mum', 'dash'] }),
      page('Then Dad snores. It is so loud!',
        'Dad snores and a big wavy swirl of sound rolls out of his mouth across the room. Picture frames tilt and Dash\'s basket rocks.',
        { cast: ['dad', 'mum', 'dash'], words: ['SNORE!'] }),
      page('The curtains flap like a sail.',
        'The bedroom curtains billow out like the sails of a ship in the gust of Dad\'s snore. A toy boat on the shelf rocks.',
        { cast: ['dad'] }),
      page('Dash shoots up into the air!',
        'Dash is blasted out of his basket, flying up into the air with his blanket flapping behind him like a cape.',
        { cast: ['dash'] }),
      page('Books and socks float round and round the room.',
        'In the children\'s bedroom next door, books, socks, teddy bears and toy cars swirl round and round the room. {hero} and {sister} sit up in bed, their hair blown back.',
        { cast: ['hero', 'sister'] }),
      page('{hero} and {sister} hang on to the bed.',
        '{hero} and {sister} cling to the bedposts, blown sideways like flags, pyjamas flapping. Dash whizzes past.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('{sister} cries out.',
        'On the landing, {sister} points at Dad\'s bedroom door with a determined face. {hero} and Dash hold on to the banister.',
        { cast: ['hero', 'sister', 'dash'], bubble: say('sister', 'We need a plan!') }),
      page('{hero} puts a sock on Dad\'s mouth.',
        '{hero} tiptoes to Dad\'s bedside and gently lays a stripy sock over Dad\'s mouth. Dash holds a torch.',
        { cast: ['hero', 'dad', 'dash'] }),
      page('SNORE! The sock shoots away like a rocket.',
        'The sock blasts off from Dad\'s mouth like a rocket with a swirly trail, past the ceiling light. {hero} and Dash duck.',
        { cast: ['hero', 'dad', 'dash'], words: ['SNORE!'] }),
      page('Then Mum sits up. She has a plan too.',
        'Mum pushes her eye mask up onto her forehead with a clever, knowing smile and one finger raised.',
        { cast: ['mum', 'dad'] }),
      page('Mum sings a soft song in Dad\'s ear.',
        'Mum leans over and sings softly into Dad\'s ear. Little music notes float in the air and Dad\'s face relaxes into a smile.',
        { cast: ['mum', 'dad'] }),
      page('Dad stops snoring. He grins in his dream.',
        'Dad sleeps peacefully, grinning. A dream cloud above his head shows him and Dash fishing on a sunny lake.',
        { cast: ['dad', 'mum'] }),
      page('At last, all is still. They creep back to bed.',
        'The toys float gently back down. {hero}, {sister} and Dash tiptoe down the moonlit landing, yawning.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('But then... SNORE! Now Mum is snoring!',
        'Mum is asleep and snoring a whistling snore that blows Dad\'s hair about. Dad is now wide awake with a pillow over his head, eyes open. Dash stands in the doorway wearing earmuffs; {hero} and {sister} giggle behind him.',
        { cast: ['mum', 'dad', 'dash', 'hero', 'sister'], words: ['SNORE!'] }),
    ],
    retell: [2, 4, 5, 9, 11, 14],
  },

  {
    id: 'pie-that-ran-away',
    blurb: 'Mum makes a jam pie for Fun Day, but Dash hides inside and the pie runs off down the street. Can {sister}\'s trail of sweets stop it?',
    level: 3,
    title: 'The Pie That Ran Away',
    cast: ['hero', 'sister', 'dad', 'mum', 'dash'],
    cover: {
      scene: 'A sunny street party with bunting. A big golden jam pie with little turquoise-green dinosaur feet sticking out underneath runs down the pavement. {hero} and {sister} chase it, laughing.',
      cast: ['hero', 'sister'],
    },
    practise: ['pie', 'tray', 'away', 'lays', 'round', 'cries', 'eat'],
    common: ['today', 'our', 'she', 'who', 'my', 'all'],
    challenge: ['after'],
    before: 'Look at the cover. How can a pie run away?',
    after: [
      'Why did the pie run away?',
      'How did {sister} stop the pie?',
      'Why did Mum put the next pie on the shed?',
      'What do you think Dash will do next?',
    ],
    pages: [
      page('Today is Fun Day on our street.',
        'A sunny British terraced street having a street party: bunting across the road, tables with tablecloths, neighbours chatting, and a big banner across the street.',
        { cast: ['hero', 'sister', 'dash'], words: ['FUN DAY'] }),
      page('Mum has a big jam pie for Fun Day.',
        'Mum proudly carries a huge golden pie with a criss-cross crust out of the front door, steam rising. {hero} and {sister} admire it.',
        { cast: ['mum', 'hero', 'sister'] }),
      page('She puts it on a tray to cool.',
        'The pie sits on a tray on the front windowsill. Dash is on the window ledge, sniffing it, his nose twitching.',
        { cast: ['dash'] }),
      page('Dash sniffs. Mmm! He creeps into the pie.',
        'Dash lifts the edge of the crust and slides inside the pie. Only his tail is still showing, and there is jam on his toes.',
        { cast: ['dash'] }),
      page('Then the pie gets up and runs away!',
        'The pie has little turquoise-green dinosaur feet sticking out underneath and is running off the tray and along the pavement, crumbs flying.',
        {}),
      page('{hero} and {sister} run after it.',
        '{hero} and {sister} chase the running pie down the street, past surprised neighbours.',
        { cast: ['hero', 'sister'], bubble: say('hero', 'Stop that pie!') }),
      page('The pie runs past a dog. The dog runs after it too!',
        'A fluffy dog joins the chase with its tongue out. A lady drops her teacup in surprise.',
        {}),
      page('The pie runs round and round a tree.',
        'A circular chase round a tree in the street: the pie, the dog and the children all running in a loop, getting dizzy.',
        { cast: ['hero', 'sister'] }),
      page('{sister} has a plan. She lays a trail of sweets.',
        '{sister} drops colourful sweets in a line along the pavement, leading to a picnic blanket. {hero} watches the pie.',
        { cast: ['hero', 'sister'] }),
      page('The pie stops to eat a sweet. Munch!',
        'The pie has stopped at a sweet, and a little dinosaur mouth peeks out from under the crust to munch it.',
        { words: ['MUNCH!'] }),
      page('{hero} lifts the top. Who is in the pie?',
        '{hero} carefully lifts the criss-cross crust like a lid. A pair of eyes glint in the dark inside.',
        { cast: ['hero', 'sister'] }),
      page('It is Dash, with jam on his cheeks!',
        'Dash sits in the pie dish covered in red jam, licking his fingers with a guilty grin.',
        { cast: ['dash', 'hero', 'sister'] }),
      page('Mum cries, "My pie!" Then all the street claps and cheers.',
        'Mum has her hands on her cheeks. Behind her the neighbours clap and laugh, and Dash takes a bow in the pie dish.',
        { cast: ['mum', 'dash', 'hero', 'sister'] }),
      page('Mum puts the next pie up high... on top of the shed!',
        `In the back garden (${HOME}), a new pie sits on the shed roof. Dash is already up there with a spoon and a napkin tied round his neck, grinning.`,
        { cast: ['dash', 'mum'], bubble: say('dash', 'Yum!'), calm: 'top-right' }),
    ],
    retell: [2, 4, 5, 8, 10, 14],
  },

  {
    id: 'blue-paw-prints',
    blurb: 'Mum\'s birthday buns have vanished! Detectives {hero} and {sister} follow a trail of blue paw prints to two very jammy suspects.',
    level: 4,
    title: 'The Blue Paw Prints',
    cast: ['hero', 'sister', 'dad', 'mum', 'dash'],
    cover: {
      scene: '{hero} and {sister} dressed as detectives, {hero} holding a big magnifying glass, follow a trail of bright blue paw prints across a kitchen floor. Dash, with bright blue paws, peeks guiltily from behind a door.',
      cast: ['hero', 'sister', 'dash'],
    },
    practise: ['blue', 'clue', 'paw', 'first', 'shirt', 'twirl', 'joy'],
    common: ['was', 'come', 'one', 'they', 'he', 'full'],
    challenge: ['birthday', 'dinosaur'],
    before: 'What does a detective do? What clues might they look for?',
    after: [
      'What was the first clue?',
      'Why did Dad have jam on his shirt?',
      'Why did Dad and Dash take the buns?',
      'Who do you think ate the missing bun?',
    ],
    pages: [
      page('It is Mum\'s birthday!',
        'A bright kitchen in the morning with balloons and a banner. Mum, in her dressing gown, smiles. {hero} and {sister} hide a present behind their backs.',
        { cast: ['mum', 'hero', 'sister'], words: ['Happy Birthday Mum'] }),
      page('But the stack of jam buns is not on the dish!',
        'An empty cake stand with only crumbs and a smear of jam. {hero} and {sister} stare at it in shock.',
        { cast: ['hero', 'sister'] }),
      page('{hero} gets a big lens.',
        '{hero} holds a big magnifying glass; {sister} wears a detective hat and holds a notepad. Dash wears a tiny detective hat too.',
        { cast: ['hero', 'sister', 'dash'], bubble: say('sister', 'Let\'s look for clues!'), words: ['clues'] }),
      page('The first clue is a blue paw print.',
        'Close-up through the magnifying glass: a small bright-blue three-toed paw print on the kitchen floor tiles.',
        { cast: ['hero'], words: ['clue'] }),
      page('Then they spot a trail of blue paw prints.',
        'A trail of blue paw prints leads across the kitchen floor and out into the hall. {hero} and {sister} follow it, bent over.',
        { cast: ['hero', 'sister'] }),
      page('The trail leads up the stairs.',
        'Blue paw prints go up the carpeted stairs. {hero} and {sister} creep up, magnifying glass first.',
        { cast: ['hero', 'sister'] }),
      page('The next clue is a bit of bun.',
        'Close-up: a crumb of bun with a blob of jam on a stair, seen through the magnifying glass.',
        { cast: ['hero'] }),
      page('Dad is on the landing. He has jam on his shirt!',
        'Dad stands at the top of the stairs trying to look innocent, hands behind his back, with a big jam smear on his shirt and a crumb on his chin.',
        { cast: ['dad'] }),
      page('{hero} looks at Dad.',
        '{hero} points the magnifying glass at Dad\'s jammy shirt. Dad looks guilty, one eyebrow raised.',
        { cast: ['hero', 'dad', 'sister'], bubble: say('hero', 'Was it you, Dad?') }),
      page('Dad grins.',
        'Dad grins sheepishly as Dash pops out from behind him with bright blue paws and blue icing on his nose.',
        { cast: ['dad', 'dash'], bubble: say('dad', 'It was me... and Dash!'), calm: 'top-right' }),
      page('Dash has blue paws and a big blue grin.',
        'Close-up of Dash holding up his bright blue paws and beaming. Behind him, a bowl of blue icing with a spoon in it.',
        { cast: ['dash'] }),
      page('Dad and Dash had a plan. Come and see!',
        `Dad and Dash lead the family down the garden path (${HOME}). Dad has a finger on his lips; Dash holds Mum's hand.`,
        { cast: ['dad', 'dash', 'mum', 'hero', 'sister'] }),
      page('It is a big bun dinosaur with a blue twirl on top!',
        'On the garden table: a dinosaur built out of jam buns, covered in swirls of blue icing, with birthday candles on its back. Mum is delighted.',
        { cast: ['mum', 'dad', 'hero', 'sister', 'dash'] }),
      page('Mum is full of joy.',
        'Mum hugs Dad, {hero} and {sister}. Dash stands on top of the bun dinosaur, waving.',
        { cast: ['mum', 'dad', 'hero', 'sister', 'dash'] }),
      page('But one bun is missing... and Dash is licking his lips!',
        'Close-up of the bun dinosaur with one obvious gap. Dash sits nearby with a round tummy, licking jam off his lips, a blue paw print on the tablecloth.',
        { cast: ['dash'] }),
    ],
    retell: [2, 4, 6, 8, 10, 13],
  },

  {
    id: 'magic-crayon',
    blurb: 'Everything {hero} draws with the magic crayon comes to life, until Dash draws a dinosaur that stomps on Dad\'s flowers. Can {hero} draw his way out of trouble?',
    level: 4,
    title: 'The Magic Crayon',
    cast: ['hero', 'sister', 'dad', 'mum', 'dash'],
    cover: {
      scene: `A sunny back garden (${HOME}). {hero} holds a glowing purple crayon. Coming to life off the paving stones is a sketchy purple crayon-scribble bird and the head of a big goofy crayon-scribble dinosaur. {sister} and Dash gasp with delight.`,
      cast: ['hero', 'sister', 'dash'],
    },
    practise: ['draws', 'claws', 'jaws', 'yawns', 'bird', 'toy', 'blue'],
    common: ['the', 'he', 'my', 'oh'],
    challenge: ['magic', 'dinosaur', 'word'],
    before: 'If you had a magic crayon, what would you draw?',
    after: [
      'What did {hero} draw first?',
      'What went wrong when Dash drew a dinosaur?',
      'How did {hero} stop the dinosaur?',
      'What would you draw with the magic crayon?',
    ],
    pages: [
      page('{hero} spots a crayon in the grass.',
        `A sunny back garden (${HOME}). {hero} kneels on the lawn and picks up a glowing purple crayon with tiny sparkles around it. Dash peers at it.`,
        { cast: ['hero', 'dash'] }),
      page('He draws a bird on the path.',
        '{hero} draws a simple bird with the purple crayon on the garden path paving stones. {sister} watches.',
        { cast: ['hero', 'sister'] }),
      page('The bird flaps up off the path! Tweet!',
        'Magic: the drawn bird peels off the path and flies up. It is a real bird made of purple crayon scribbles, leaving a sparkly trail. The children gasp.',
        { cast: ['hero', 'sister'], words: ['TWEET!'] }),
      page('It is a magic crayon!',
        '{hero} and {sister} stare at the crayon in awe while the crayon bird circles their heads. {sister} reaches out eagerly.',
        { cast: ['hero', 'sister', 'dash'], bubble: say('sister', 'My turn!') }),
      page('{sister} draws a blue toy car. Beep, beep!',
        'A blue crayon-scribble toy car zooms off the path with Dash riding on top, arms up. {sister} cheers.',
        { cast: ['sister', 'dash'], words: ['BEEP!'] }),
      page('Dash draws a big, big dinosaur.',
        'Dash holds the crayon with both hands (it is nearly as big as him) and draws a huge dinosaur outline across the whole path. {hero} and {sister} look worried.',
        { cast: ['dash', 'hero', 'sister'] }),
      page('It has sharp claws and big jaws.',
        'The drawn dinosaur outline glows purple. You can see its sharp claws and big jaws drawn in scribbly crayon lines.',
        { cast: ['dash'] }),
      page('ROAR! It stomps off the path.',
        'A giant purple crayon-scribble dinosaur, goofy rather than scary, rears up off the path and roars. Leaves blow back; the children jump.',
        { cast: ['hero', 'sister', 'dash'], words: ['ROAR!'] }),
      page('It stomps on Dad\'s flowers!',
        'The crayon dinosaur stomps across Dad\'s flower bed, petals flying. Dad is at the kitchen window with a mug and has not noticed yet.',
        { cast: ['dad'] }),
      page('But the dinosaur will not stop.',
        '{sister} holds up her hands and shouts at the crayon dinosaur, which is happily trampling the flowers.',
        { cast: ['sister'], bubble: say('sister', 'Stop!') }),
      page('{hero} has a plan. He draws a big soft bed.',
        '{hero} draws a huge cosy bed with a pillow on the lawn using the crayon, with a determined face.',
        { cast: ['hero'] }),
      page('Then he draws a word on it: NAP.',
        'Close-up: big glowing purple crayon letters drawn on the blanket of the crayon bed.',
        { cast: ['hero'], words: ['NAP'] }),
      page('The dinosaur yawns. It curls up and naps.',
        'The crayon dinosaur curls up in the crayon bed, snoring gently. The crayon bird perches on its head. The children tiptoe past.',
        { cast: ['hero', 'sister', 'dash'], words: ['Zzz'] }),
      page('{hero} and {sister} fix Dad\'s flowers.',
        '{hero} and {sister} draw new flowers in the flower bed; they pop up as bright crayon flowers.',
        { cast: ['hero', 'sister'], bubble: say('hero', 'Shhh!') }),
      page('But now Dash has the crayon. Uh oh!',
        'Dash runs off behind a bush with the crayon, where he is drawing a mountain of ice creams with a cheeky grin. In the background {hero} and {sister} notice, hands on heads.',
        { cast: ['dash', 'hero', 'sister'] }),
    ],
    retell: [2, 5, 8, 9, 12, 15],
  },

  {
    id: 'dash-grew-and-grew',
    blurb: 'Dash slurps Dad\'s new plant food and grows as big as the house. {hero} reads the label on the jar to find out how to shrink him.',
    level: 5,
    title: 'Dash Grew and Grew',
    cast: ['hero', 'sister', 'dad', 'mum', 'dash'],
    cover: {
      scene: `A giant Dash, taller than ${HOME}, peeks over the roof next to the chimney with a bird's nest on his head. The family stand tiny on the pavement below, looking up in amazement.`,
      cast: ['dash', 'hero', 'sister', 'dad', 'mum'],
    },
    practise: ['new', 'grew', 'blew', 'whoosh', 'chimney', 'toes', 'phew', 'August'],
    common: ['one', 'people', 'what', 'they', 'little', 'again', 'house'],
    challenge: ['tickle', 'leaves'],
    before: 'What do plants need to grow? What would happen if a dinosaur drank plant food?',
    after: [
      'What made Dash grow?',
      'How did {hero} find out how to shrink Dash?',
      'What happened to Dad\'s plants?',
      'What would you do if you were as big as a house?',
    ],
    pages: [
      page('It is a hot day in August. Dad has a new jar of plant food.',
        `A hot sunny garden (${HOME}). Dad stands by the shed holding a jar with a green label, next to a few droopy plants in pots. Dash watches from a flower pot.`,
        { cast: ['dad', 'dash'], words: ['GROW'] }),
      page('One drop, and his plants grew and grew!',
        'Dad squeezes one drop from a dropper into a pot and the plant shoots up into a huge leafy plant, blowing his hair back.',
        { cast: ['dad'] }),
      page('Then Dash spots the jar. Slurp!',
        'Dash tips up the jar of plant food and drinks from it, green drips on his chin. Nobody is watching.',
        { cast: ['dash'], words: ['SLURP!'] }),
      page('Dash grew... and grew... and GREW!',
        'Dash grows bigger in the garden with motion lines, now as tall as the shed, looking surprised at his own size.',
        { cast: ['dash'] }),
      page('Now he is as big as the house, next to the chimney!',
        `Giant Dash stands in the back garden, his head above the roof of ${HOME} next to the chimney, with a bird's nest on his head. The family stand tiny below, looking up.`,
        { cast: ['dash', 'hero', 'sister', 'dad', 'mum'] }),
      page('Whoosh! He blew the leaves off the trees.',
        'Giant Dash blows a big puff of air and leaves swirl off the trees down the street. Washing flies off a washing line.',
        { cast: ['dash'], words: ['WHOOSH!'] }),
      page('He is as big as ten buses!',
        'Giant Dash sits in the street; a red double-decker bus parked next to him looks like a toy. The bus driver stares.',
        { cast: ['dash'] }),
      page('People come out to look.',
        'Neighbours in dressing gowns and slippers stand on the pavement pointing up at giant Dash. A dog barks.',
        { cast: ['dash'] }),
      page('What can they do?',
        'The family huddles in the garden looking up at giant Dash, who looks a bit worried too. Dad holds the jar.',
        { cast: ['hero', 'sister', 'dad', 'mum', 'dash'], bubble: say('sister', 'How can we get Dash small again?') }),
      page('{hero} reads the back of the jar.',
        '{hero} holds the jar and reads the label on the back, one finger under the words. {sister} leans in.',
        { cast: ['hero', 'sister'], words: ['TO SHRINK: TICKLE TOES'] }),
      page('"Tickle his toes!" {hero} shouts.',
        '{hero} shouts with excitement, pointing at giant Dash\'s huge feet.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('Mum, Dad, {hero} and {sister} tickle Dash\'s big toes.',
        'The whole family tickles giant Dash\'s toes with feathers and fingers. Dash giggles, with happy tears of laughter.',
        { cast: ['mum', 'dad', 'hero', 'sister', 'dash'] }),
      page('Hee, hee, hee! Dash shrinks... and shrinks... and shrinks!',
        'Dash shrinks back down in stages, laughing all the way.',
        { cast: ['dash', 'hero', 'sister'] }),
      page('Phew! Dash is little again.',
        'Tiny Dash sits in {sister}\'s cupped hands; everyone looks relieved. The jar is safely on a high shelf in the shed.',
        { cast: ['sister', 'dash', 'hero', 'dad', 'mum'] }),
      page('But Dad\'s plants are as big as the house now!',
        `The plants in the garden have grown into giant sunflowers and beanstalks towering over ${HOME}. Dad's mouth is wide open. Dash is already climbing up one with a grin.`,
        { cast: ['dad', 'dash'] }),
    ],
    retell: [2, 4, 5, 10, 12, 15],
  },

  {
    id: 'rocket-launch',
    blurb: 'A big box becomes a rocket, and the rocket really launches! A trip to the moon, a donkey astronaut and a crew of moon frogs, all before tea.',
    level: 5,
    title: 'Rocket Launch!',
    cast: ['hero', 'sister', 'dad', 'mum', 'dash'],
    cover: {
      scene: `A cardboard-box rocket with paper-plate fins blasts off over the back garden (${HOME}) in a burst of sparkles. {hero}, {sister} and Dash wave from its round window. Dad snoozes in a deckchair below.`,
      cast: ['hero', 'sister', 'dash', 'dad'],
    },
    practise: ['launch', 'whoosh', 'donkey', 'crew', 'zoom', 'clouds', 'hear'],
    common: ['there', 'two', 'one', 'they', 'all', 'who'],
    challenge: ['rocket', 'asleep'],
    before: 'What would you need to make a rocket out of a box?',
    after: [
      'What did they make the rocket from?',
      'Who did they meet on the moon?',
      'Why did they zoom home?',
      'Where would you go in a rocket?',
    ],
    pages: [
      page('There is a big box in the garden.',
        `A huge empty cardboard box on the lawn of the back garden (${HOME}). {hero} and {sister} peek out of it; Dash sits on top.`,
        { cast: ['hero', 'sister', 'dash'] }),
      page('{hero} and {sister} turn it into a rocket.',
        '{hero} and {sister} paint the box: a pointy cardboard nose cone, a round window and fins made from paper plates. Paint splodges everywhere; Dash holds a paint brush in his mouth.',
        { cast: ['hero', 'sister', 'dash'], words: ['ROCKET'] }),
      page('Dash paints stars on it. They look cool!',
        'Dash paints yellow stars all over the rocket, and one on {sister}\'s cheek.',
        { cast: ['dash', 'sister', 'hero'] }),
      page('Three, two, one...',
        'Inside the box rocket: {hero}, {sister} and Dash wear colander helmets and goggles. {hero} presses a bottle-top button; Dash counts on his claws. A toy walkie-talkie sits on the dashboard.',
        { cast: ['hero', 'sister', 'dash'], bubble: say('hero', 'Launch!') }),
      page('WHOOSH! The rocket shoots up into the clouds!',
        'Magic: the cardboard rocket blasts off from the garden with a flame of sparkles. Below, Dad is asleep in a deckchair and his newspaper blows away.',
        { cast: ['dad'], words: ['WHOOSH!'] }),
      page('They zoom past the moon.',
        'Space: the cardboard rocket zips past a big silvery moon with the blue Earth glowing behind. Excited faces at the round window.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('Bump! They land on the moon.',
        'The rocket has landed in a moon crater with a puff of moon dust. {hero}, {sister} and Dash step out in their colander helmets.',
        { cast: ['hero', 'sister', 'dash'], words: ['BUMP!'] }),
      page('A donkey with a jet pack zooms up to them.',
        'A friendly donkey astronaut in a white space suit and jet pack, his long ears poking up inside a round fishbowl helmet, waves at them. The children are amazed.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('The donkey has a crew of moon frogs.',
        'A crew of tiny glowing green moon frogs in little helmets hop around the astronaut donkey in low gravity.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('They all jump and jump. Up, up, up!',
        'Everyone bounces super high in the low gravity: Dash does a somersault, moon frogs hop, the Earth glows in the sky.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('Then they hear Mum shout.',
        '{hero} holds a toy walkie-talkie that crackles with Mum\'s voice. Everyone stops bouncing in mid-air.',
        { cast: ['hero', 'sister', 'dash'], bubble: say('mum', 'Tea!') }),
      page('They hug the donkey and zoom back down.',
        '{hero} and {sister} hug the astronaut donkey goodbye while the moon frogs wave. The rocket is blasting off from the moon.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('Crash! They land in Dad\'s flower bed.',
        'The cardboard rocket lands nose-down in Dad\'s flower bed, a bit crumpled, and the children climb out laughing. Petals fly.',
        { cast: ['hero', 'sister', 'dash'], words: ['CRASH!'] }),
      page('Dad is still asleep. He did not see a thing!',
        'Dad snoozes in his deckchair with a newspaper on his tummy, completely unaware.',
        { cast: ['dad'] }),
      page('But who is that on Dad\'s hat? A moon frog!',
        'A tiny glowing moon frog sits on top of Dad\'s sun hat, waving at the reader. Dash points at it with a grin; {hero} and {sister} giggle with hands over their mouths.',
        { cast: ['dad', 'dash', 'hero', 'sister'] }),
    ],
    retell: [2, 5, 8, 9, 13, 15],
  },

  {
    id: 'dash-goes-home',
    blurb: 'Dash misses his mum, so {hero} and {sister} build a time machine in Dad\'s shed and take him back to the land of the dinosaurs.',
    level: 6,
    title: 'Dash Goes Home',
    cast: ['hero', 'sister', 'dad', 'mum', 'dash'],
    cover: {
      scene: 'A little wooden garden shed sits among giant ferns in a sunny prehistoric valley with a distant volcano. Dash stands nose to nose with his giant mum, who looks like a grown-up Dash. {hero} and {sister} watch from the shed doorway, smiling.',
      cast: ['dash', 'dashMum', 'hero', 'sister'],
    },
    practise: ['home', 'take', 'make', 'time', 'shakes', 'these', 'smiles', 'nose', 'wave'],
    common: ['says', 'have', 'come', 'two', 'push', 'she', 'so'],
    challenge: ['machine', 'dinosaur', 'dinosaurs', 'Sundays'],
    before: 'Where do you think Dash came from? Who might he miss?',
    after: [
      'Why was Dash sad?',
      'How did they get to the land of dinosaurs?',
      'How did {hero} feel when Dash found his mum?',
      'What do you think Dash does on Sundays?',
    ],
    pages: [
      page('Dash is sad. He misses his home and his mum.',
        'A rainy afternoon in {hero}\'s bedroom. Dash sits on the windowsill watching the rain, a tear on his cheek, holding a drawing of a big dinosaur. {hero} and {sister} notice.',
        { cast: ['dash', 'hero', 'sister'] }),
      page('{hero} has a plan.',
        '{hero} kneels by Dash with a hand on his back and a kind smile. {sister} holds a toolbox.',
        { cast: ['hero', 'sister', 'dash'], bubble: say('hero', 'We can take you home!') }),
      page('They make a time machine in Dad\'s shed.',
        'The garden shed turned into a time machine: an old armchair, a wall of dials, levers and blinking fairy lights, an old clock and tin cans. {hero} and {sister} hold screwdrivers; Dash plugs in a cable.',
        { cast: ['hero', 'sister', 'dash'], words: ['TIME MACHINE'] }),
      page('{hero} presses the big red button.',
        'Close-up of {hero}\'s finger pressing a big red button with a label. Dash and {sister} hold on tight.',
        { cast: ['hero', 'sister', 'dash'], words: ['DINO TIME'] }),
      page('The shed shakes. Flash! Bang!',
        'The shed shakes, with swirling rainbow light pouring out of the window and the gaps in the planks. Garden tools rattle.',
        { words: ['FLASH!', 'BANG!'] }),
      page('They step out. These trees are so tall, and these dinosaurs are so big!',
        'A breathtaking prehistoric valley: giant ferns and tall trees, a smoking volcano far away, long-necked dinosaurs drinking from a lake and flying reptiles in the sky. The little shed sits among the ferns; {hero}, {sister} and Dash stand in the doorway, amazed.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('Dash smiles. He is home at last!',
        'Dash runs ahead through the ferns with his arms out, smiling hugely.',
        { cast: ['dash'] }),
      page('Then they spot a dinosaur next to the lake. She is as big as a bus!',
        'Dash\'s mum stands beside a lake, turning her head towards them.',
        { cast: ['dashMum', 'hero', 'sister', 'dash'] }),
      page('It is Dash\'s mum!',
        'Dash and his huge mum see each other: joyful recognition. {hero} and {sister} grin.',
        { cast: ['dash', 'dashMum', 'hero', 'sister'], bubble: say('dash', 'Mum!') }),
      page('Dash runs to his mum. She rubs her nose on him.',
        'Dash\'s giant mum gently nuzzles tiny Dash with her big nose. Little hearts float in the air; {hero} and {sister} smile with happy tears.',
        { cast: ['dash', 'dashMum', 'hero', 'sister'] }),
      page('{hero} is glad. But he is sad too. He will miss Dash.',
        '{hero} smiles but his chin wobbles. {sister} holds his hand.',
        { cast: ['hero', 'sister'] }),
      page('Dash\'s mum smiles. She pushes Dash back to {hero}.',
        'Dash\'s mum gently nudges Dash towards {hero} with her nose. Dash looks back and forth between them.',
        { cast: ['dashMum', 'dash', 'hero', 'sister'] }),
      page('She nods and says...',
        'Dash\'s mum nods warmly. Dash hugs {hero}\'s leg happily.',
        { cast: ['dashMum', 'dash', 'hero', 'sister'], bubble: say('dashMum', 'Go and have fun. Come home on Sundays!') }),
      page('They wave and step back into the shed.',
        '{hero}, {sister} and Dash wave from the shed door; Dash\'s mum waves her tail. The sun sets over the valley.',
        { cast: ['hero', 'sister', 'dash', 'dashMum'] }),
      page('So now Dash has two homes!',
        'Back home in {hero}\'s bedroom at night: Dash asleep in Dad\'s floppy hat on the bed. A calendar on the wall has the Sundays circled with dinosaur stickers, and a photo of Dash with his mum stands on the shelf. Through the window, a tiny dinosaur tail pokes out of the shed.',
        { cast: ['dash', 'hero'] }),
    ],
    retell: [1, 3, 5, 6, 10, 15],
  },

  {
    id: 'snowman-in-the-freezer',
    blurb: 'A snowman comes to life on a snow day. When the sun comes out and he starts to melt, {hero} has a cool idea: the freezer!',
    level: 6,
    title: 'The Snowman in the Freezer',
    cast: ['hero', 'sister', 'dad', 'mum', 'dash'],
    cover: {
      scene: 'A family kitchen. A cheerful snowman with a carrot nose and stick arms waves from inside an open chest freezer, next to bags of frozen peas. Dad jumps back in surprise. {hero}, {sister} and Dash laugh behind the door.',
      cast: ['dad', 'hero', 'sister', 'dash'],
    },
    practise: ['white', 'make', 'nose', 'stones', 'smiles', 'slide', 'skate', 'save'],
    common: ['they', 'have', 'oh', 'comes', 'two', 'puts'],
    challenge: ['snow', 'snowman', 'snowball', 'carrot', 'freezer', 'melting'],
    before: 'What happens to a snowman when the sun comes out?',
    after: [
      'What made the snowman come alive?',
      'Why was the snowman melting?',
      'How did {hero} save him?',
      'What would you do with a snowman friend?',
    ],
    pages: [
      page('It is a snow day! The garden is white.',
        `The back garden (${HOME}) covered in thick snow, flakes falling, the shed with a snowy roof. {hero} and {sister} in coats, hats and wellies burst out of the back door; Dash wears a tiny woolly hat and scarf.`,
        { cast: ['hero', 'sister', 'dash'] }),
      page('{hero} and {sister} make a snowman.',
        '{hero} and {sister} roll a big snowball for the body while Dash rolls a small one for the head.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('Dash puts on a carrot nose and two stones.',
        'Dash stands on {hero}\'s shoulders pushing a carrot nose into the snowman\'s face. Two dark stones are the eyes and sticks are the arms.',
        { cast: ['dash', 'hero', 'sister'] }),
      page('Then the snowman blinks... and smiles!',
        'Magic: the snowman\'s stone eyes blink and a big smile spreads across his face. {hero}, {sister} and Dash jump back in amazement among a few sparkles.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('The snowman waves his stick arms.',
        'The snowman waves his twiggy arms happily. The children are delighted.',
        { cast: ['hero', 'sister', 'dash'], bubble: say('snowman', 'Let\'s play!'), calm: 'top-right' }),
      page('They slide down the hill on a tray.',
        'A snowy park hill: the snowman slides down on a big tea tray with {hero}, {sister} and Dash piled on behind him, everyone cheering, snow spraying.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('They skate on the pond.',
        'A frozen pond: the snowman skates gracefully, the children wobble, and Dash spins on his tail.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('They have a snowball game. The snowman wins!',
        'A snowball game: the snowman juggles three snowballs while {hero} and {sister} duck behind a snow wall, laughing.',
        { cast: ['hero', 'sister', 'dash'] }),
      page('The next day, the sun comes out. Drip, drip, drip...',
        'A bright sunny morning, snow melting from the roofs. The snowman in the garden has drips running down him and looks worried; his carrot nose droops.',
        { words: ['DRIP!'] }),
      page('{sister} runs out to the snowman.',
        '{sister} runs across the slushy garden in pyjamas and wellies, looking worried.',
        { cast: ['sister'], bubble: say('sister', 'Oh no! He is melting!') }),
      page('{hero} has a plan. The freezer!',
        '{hero} has a lightbulb-moment face, pointing towards the kitchen. Dash nods.',
        { cast: ['hero', 'dash', 'sister'], bubble: say('hero', 'We must save him!') }),
      page('They tuck the snowman in the freezer, next to the peas.',
        'In the kitchen: a big chest freezer open with frosty mist. The snowman, a little smaller now, is tucked inside smiling, next to bags of peas and a tub of ice cream. The children gently lower the lid.',
        { cast: ['hero', 'sister', 'dash'], words: ['peas', 'ice cream'] }),
      page('Then Dad gets the peas for tea.',
        'Evening: Dad in an apron opens the chest freezer lid and reaches in without looking, whistling. {hero} and {sister} hide behind the kitchen door, giggling; Dash peeks out.',
        { cast: ['dad', 'hero', 'sister', 'dash'] }),
      page('AAAH! The snowman waves at Dad!',
        'Dad jumps back in shock and frozen peas fly everywhere. The snowman in the freezer cheerfully waves, a pea on his carrot nose. The children and Dash laugh.',
        { cast: ['dad', 'hero', 'sister', 'dash'], words: ['AAAH!'] }),
      page('Now the snowman is safe... and Dad has a new pal!',
        'Dad laughs and shares an ice lolly with the snowman at the open freezer. The whole family gathers round, Mum included.',
        { cast: ['dad', 'mum', 'hero', 'sister', 'dash'] }),
    ],
    retell: [2, 4, 6, 9, 12, 14],
  },
];
